// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmxq03xZglBjbC9a2n__asEhhOoUJ5IA',
    appId: '1:372093744671:web:733f0bf6590ede3fc0872a',
    messagingSenderId: '372093744671',
    projectId: 'study-app-9dd70',
    authDomain: 'study-app-9dd70.firebaseapp.com',
    storageBucket: 'study-app-9dd70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlqimBN_0K7FcHt4ukfTN4gIg6DUJqu0',
    appId: '1:372093744671:android:ce9a4ac283ab8493c0872a',
    messagingSenderId: '372093744671',
    projectId: 'study-app-9dd70',
    storageBucket: 'study-app-9dd70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZ-mAndEHr9VGEkVH8Rt9AltOVpDz8lY',
    appId: '1:372093744671:ios:7a6ccba43357e21ac0872a',
    messagingSenderId: '372093744671',
    projectId: 'study-app-9dd70',
    storageBucket: 'study-app-9dd70.appspot.com',
    iosClientId: '372093744671-rccl21e1ses62mlfrkdeil9neqmkd096.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
